### ISSUE TITLE
any plans for a simple gradio web ui?

### ISSUE THREAD

**Issue by cocktailpeanut** [wenqsun/DimensionX#2]

**Comment by wenqsun** [comment]
Thanks for your suggestion! We will release the gradio demo in three or four days! 

Also, we will release more checkpoints soon!

**Comment by keyonchrist** [comment]
> Thanks for your suggestion! We will release the gradio demo in three or four days!
> 
> Also, we will release more checkpoints soon!

amazing! when will more checkpoints come! such an amazing job here guys

**Comment by xiao2mo** [comment]
awesome work!! Look forward for it!!!

**Comment by wenqsun** [comment]
Hi, we have released a gradio web ui, you can try it now!

Also, we have released one more ckpt: orbit up. More models will be open soon!

**Comment by keyonchrist** [comment]
> Hi, we have released a gradio web ui, you can try it now!
> 
> Also, we have released one more ckpt: orbit up. More models will be open soon!

Awesome! cant wait to try orbit up!
