### ISSUE TITLE
How can I get the cam pos?

### ISSUE THREAD

**Issue by huahuo359** [wenqsun/DimensionX#22]
I want to reconstruct 3DGS from the generated video, how can I set the cam pose correctly？

**Comment by chenshuo20** [comment]
You can consider using [dust3r](https://github.com/naver/dust3r) to estimate camera poses, or use COLMAP. For detailed guidance, refer to the instructions provided in the [3DGS repository](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#processing-your-own-scenes). For a more detailed explanation of the reconstruction process, please refer to our paper.

**Comment by huahuo359** [comment]
Thank you for your answer, Does this mean that the generated muti view does not have a fixed view like sv3d or zero123++?

**Comment by chenshuo20** [comment]
Correct.
