### ISSUE TITLE
is the video format is the only option for generated output?

### ISSUE THREAD

**Issue by quanchentg** [wenqsun/DimensionX#25]
This project is awesome!
I would like to ask if the output can be in the format of.obj or .glb or any other 3D model format rather than videos?Thank you.

**Comment by chenshuo20** [comment]
You can use the output video to reconstruct the scene with 3DGS. In our paper, we utilize DUSt3R and 3DGS optimization to reconstruct the 3D scene. We plan to open-source our 3DGS optimization code in the future.
