### ISSUE TITLE
Could you share a requirements.txt or pyproject.toml file

### ISSUE THREAD

**Issue by wy** [wenqsun/DimensionX#3]
Getting this error currently
```
a_base.py", line 445, in fuse_lora
    raise ValueError(f"{fuse_component} is not found in {self._lora_loadable_modules=}.")
ValueError: text_encoder is not found in self._lora_loadable_modules=['transformer'].
(dimensionx-video-py3.12) 
```

**Comment by chenshuo20** [comment]
You can skip the text encoder part in fuse_lora() in src/diffusers/loaders/lora_base.py like:
```
for fuse_component in components:
    if fuse_component == 'text_encoder':
    continue
```

For more details you can check this [issue](https://github.com/THUDM/CogVideo/issues/352).

And we will provide more detailed information about the environment as soon as possible.
