### ISSUE TITLE
Question about the number of images generated

### ISSUE THREAD

**Issue by BoMingZhao** [wenqsun/DimensionX#31]
Thanks for your impressive work!
I used your provide checkpoints to generate a 6 seconds (default settings, 49 frames) video, which is pretty good. 
However, when I try to change the num_frames, the results becomes very strange. Actually I tried num_frames=8, 9, 12, 13,41,48, which is all failed.
![image](https://github.com/user-attachments/assets/ad97b49b-3890-485a-8d45-30df1e42345f)

So how to use this parameter?

**Comment by chenshuo20** [comment]
CogVideoX-I2V uses 3D RoPE position embeddings, which are fixed, so the number of frames cannot be changed and it only accepts 49 frames at this time. Future versions of CogvideoX may support generation with variable frame lengths. You can find their update [here](https://github.com/THUDM/CogVideo).

**Comment by BoMingZhao** [comment]
> CogVideoX-I2V uses 3D RoPE position embeddings, which are fixed, so the number of frames cannot be changed and it only accepts 49 frames at this time. Future versions of CogvideoX may support generation with variable frame lengths. You can find their update [here](https://github.com/THUDM/CogVideo).

Thanks
